Repository AISC-25SS/order-system-study, pull requests merged in 2025-05, with the labels that each got.

#8 feat: ItemRepository 구현
  src/Item/ItemRepository.java
Labels: ✨ feat, 👤 성빈

#17 Member 엔티티 인터페이스 추가
  src/member/Grade.java
  src/member/Member.java
  src/member/MemberRepository.java
  src/member/MemberService.java
  src/member/MemberServiceImpl.java
  src/member/MemberUI.java
  src/member/MemoryMemberRepository.java
Labels: ✨ feat, 👤 승준

#11 feat/#10 order domain
  .idea/misc.xml
  src/order/Order.java
Labels: ✨ feat, 👤 종현
